[theme]
base="light"
primaryColor="#0A3956"
backgroundColor="#FFFFFF"
textColor="#000000"
secondaryBackgroundColor="#dbe1f5"

[client]
showSidebarNavigation=true

[server]
maxUploadSize=1000
maxMessageSize=1000
